export const loginActions = {
  CHANGED_MESSAGE: "login/CHANGED_MESSAGE",
  CHANGED_ISLOGGIN: "login/CHANGED_ISLOGGIN"
};

export const usersActions = {
  LOAD_DATA: "users/LOAD_DATA",
  CHANGED_SEARCH: "users/CHANGED_SEARCH",
  TOGGLE_LOADING: "users/TOGGLE_LOADING",
  SELECTED_USER: "users/SELECTED_USER",
  SET_FIRST_NAME: "users/SET_FIRST_NAME",
  SET_LAST_NAME: "users/SET_LAST_NAME",
  SET_AVATAR: "users/SET_AVATAR"
};
